# Generated by Django 2.1.4 on 2020-03-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsonsale',
            name='marketprice1',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='goodsonsale',
            name='marketprice2',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='goodsonsale',
            name='marketprice3',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trolley',
            name='productprice',
            field=models.FloatField(max_length=10),
        ),
    ]
