# Generated by Django 2.1.4 on 2020-03-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_auto_20200319_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='marketprice',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsonsale',
            name='marketprice1',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsonsale',
            name='marketprice2',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsonsale',
            name='marketprice3',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsonsale',
            name='price1',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsonsale',
            name='price2',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsonsale',
            name='price3',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trolley',
            name='productprice',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
