# Generated by Django 2.1.4 on 2020-03-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0003_goodsonsale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsonsale',
            old_name='trackid',
            new_name='track_id',
        ),
    ]
